# Config

# Site settings
url: https://domain.com # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
title: 
description: > # this means to ignore newlines until "theme_color:"

# Home Sections
sections:
  - title: Call To Action
    filename: call-to-action.html
  - title: Services
    filename: services.html
  - title: Portfolio
    filename: portfolio.html
  - title: Aside
    filename: aside.html

copyright: © 2019. All rights reserved.

# Build settings
markdown: kramdown
